/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pengyouwan_sdk_utils_SecretUtil */

#ifndef _Included_com_pengyouwan_sdk_utils_SecretUtil
#define _Included_com_pengyouwan_sdk_utils_SecretUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pengyouwan_sdk_utils_SecretUtil
 * Method:    doA
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_pengyouwan_sdk_utils_SecretUtil_doA
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_pengyouwan_sdk_utils_SecretUtil
 * Method:    doB
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_pengyouwan_sdk_utils_SecretUtil_doB
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_pengyouwan_sdk_utils_SecretUtil
 * Method:    getA
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pengyouwan_sdk_utils_SecretUtil_getA
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_pengyouwan_sdk_utils_SecretUtil_getB
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
